### ISSUE TITLE
Request: Create shared Dashboards for players.

### ISSUE THREAD

**Issue by GuillermoBallonV** [RobertTate/dashboard-maker#1]
It would be awesome to allow you as a DM to tag a Dashboard 'public' to let players access it and review it. For homebrew rules or reminders :)

**Comment by RobertTate** [comment]
Agreed. This would be very cool! I can't promise anything, but I will look a bit into what would be involved. I'm thinking some sort of push system. Gotta scan the Owlbear docs again to see if their API has any sort of transport mechanism to support this 😃

**Comment by RobertTate** [comment]
@GuillermoBallonV so I just added a feature to accomplish "public" dashboards. 

- https://github.com/RobertTate/dashboard-maker/pull/5

Let me know what you think!
